my_str = 'mysooru'
print(my_str)
print(my_str[:])
print(my_str[:6])
print(my_str[1:5])
print(my_str[5:2])
print(my_str[:6:2])
print(my_str[6::-2])
print(len(my_str[-1:0]))
print(my_str[::-1])
print(my_str[:20])
print(my_str[:10])